### PR TITLE
Bootstrap 4 support + latest Datatables

### PR DESCRIPTION
**Pull request by djibe**

### CODE REVIEW

**Comment by derekeder** [comment]
thanks for this PR @djibe! I'll plan to review it next week.

**Comment by djibe** [comment]
@derekeder Hi, did you have the time to merge commits ?
Thanks for your work.

**Review by derekeder — APPROVED** [review]
@djibe my apologies for the delay on reviewing this PR. I checked it out and all the changes look great. merging in!

**Comment by djibe** [comment]
Hi,
so funny ! Completely forgot about your awesome work.
I improved the design, you may look at my demo page: https://djibe.github.io/material/docs/4.6/plugins/datatables/

Thx for your work

**Comment by derekeder** [comment]
@djibe wow very nice work! thanks for your contributions!

**Pull request merged**
